"""Commit message

Revision ID: 4e73a9a122db
Revises: 3ddb763db202
Create Date: 2020-09-19 10:48:08.528723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e73a9a122db'
down_revision = '3ddb763db202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cart_items', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'cart_items', 'dishes', ['dish_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    # ### end Alembic commands ###
