"""Commit message

Revision ID: d5c0c118b111
Revises: 4e73a9a122db
Create Date: 2020-09-23 16:33:58.949313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c0c118b111'
down_revision = '4e73a9a122db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dishes', 'quantity')
    op.drop_column('orders', 'distance')
    op.drop_column('users', 'accept_policy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('accept_policy', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('distance', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.add_column('dishes', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
